service: "ignitecertificate"

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/users_certificates"
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*"

package:
  patterns:
    - "src/templates"

custom:
  esbuild:
    packager: yarn
    external:
      - "puppeteer-core"
      - "chrome-aws-lambda"
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  generateCertificate:
    handler: src/functions/generateCertificate.handle
    events:
      - http:
          method: "POST"
          path: "/generateCertificate"
          cors: true
  verifyCertificate:
    handler: src/functions/verifyCertificate.handle
    events:
      - http:
          method: "GET"
          path: "/verifyCertificate/{id}"
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_certificates
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
